[server]
host = "0.0.0.0"
port = 40056

[server.ssl-cert]
cert = "data/certs/default.crt"
key  = "data/certs/default.key"

[[operator]]
username = "5pider"
password = "password1234"

[[operator]]
username = "Paul"
password = "password1234"

