[server]
host = "0.0.0.0"
port = 40056
plugins = [
  "../kaine-kit/bin/http.hp",
  "../kaine-kit/bin/kaine.hp"
]

[[operator]]
username = "5pider"
password = "password1234"

[[operator]]
username = "Paul"
password = "password1234"


