[server]
host = "0.0.0.0"
port = 40056
plugins = [
  "../kaine-kit/plugins/http.hp",
  "../kaine-kit/plugins/kaine.hp",
  "../kaine-kit/plugins/smb.hp"
]

[[operator]]
username = "5pider"
password = "password1234"

[[operator]]
username = "Paul"
password = "password1234"


